# WordPress local development environment
# WARNING: DO NOT USE IN PRODUCTION WITHOUT MODIFICATION!

version: "2"

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: WORDPRESS_DEV_MYSQL_00
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:php7.2-apache
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8282:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8383:80"
    depends_on:
      - db
volumes:
  db_data:
